# -*- coding: utf-8 -*-
"""ufd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LqOtZUansGie04WSOVg_S7cXFjNKMYCI
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

num_transactions = 100000
num_users = 2000
num_devices = 3000
num_merchants = 500

users = [f"user_{i}" for i in range(num_users)]
devices = [f"device_{i}" for i in range(num_devices)]
merchants = [f"merchant_{i}" for i in range(num_merchants)]
cities = ["Chennai","Mumbai","Delhi","Bangalore","Hyderabad","Pune","Kolkata"]

start_date = datetime(2025,1,1)
timestamps = [
    start_date + timedelta(minutes=random.randint(0, 500000))
    for _ in range(num_transactions)
]

amounts = np.random.exponential(scale=2000, size=num_transactions)
amounts = np.clip(amounts,10,50000)

user_ids = np.random.choice(users, num_transactions)
device_ids = np.random.choice(devices, num_transactions)
merchant_ids = np.random.choice(merchants, num_transactions)
city = np.random.choice(cities, num_transactions)

hour = [t.hour for t in timestamps]

device_change = np.random.choice([0,1], num_transactions, p=[0.9,0.1])

geo_change = np.random.choice([0,1], num_transactions, p=[0.92,0.08])

fraud_flag = np.random.choice([0,1], num_transactions, p=[0.97,0.03])

for i in range(num_transactions):
  if device_change[i] == 1 and geo_change[i] == 1 and amounts[i] > 10000:
        fraud_flag[i] = 1

data = pd.DataFrame({
    "transaction_id": range(num_transactions),
    "user_id": user_ids,
    "timestamp": timestamps,
    "amount": amounts,
    "merchant_id": merchant_ids,
    "device_id": device_ids,
    "city": city,
    "hour": hour,
    "device_change": device_change,
    "geo_change": geo_change,
    "fraud_flag": fraud_flag
})

data.to_csv("upi_transactions.csv", index=False)

data.head()

pip install dask[complete]

import dask.dataframe as dd
import pandas as pd

df = dd.read_csv("upi_transactions.csv")

df.head()

df.columns

df.shape

df.shape[0].compute()

df.isnull().sum().compute()

df = df.dropna()

df['timestamp'] = dd.to_datetime(df['timestamp'])

df['hour'] = df['timestamp'].dt.hour
df['day'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month

df[['timestamp','hour','day']].head()

df['fraud_flag'].value_counts().compute()

df['amount'].describe().compute()

txn_per_user = df.groupby("user_id").transaction_id.count().compute()

txn_per_user.head()

txn_count = df.groupby("user_id").transaction_id.count().rename("txn_frequency")
df = df.merge(txn_count.to_frame(), on="user_id")

df.head()

pdf = df.compute()

type(pdf)

pdf = df.compute()

pdf['fraud_flag'].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt
sns.boxplot(x="fraud_flag", y="amount", data=pdf)
plt.show()

sns.countplot(x="hour", hue="fraud_flag", data=pdf)
plt.show()

sns.countplot(x="device_change", hue="fraud_flag", data=pdf)
plt.show()

sns.countplot(x="geo_change", hue="fraud_flag", data=pdf)
plt.show()

features = ["amount","hour","device_change","geo_change","txn_frequency"]
X = pdf[features]
y = pdf["fraud_flag"]

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
sns.heatmap(pdf[features + ["fraud_flag"]].corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("Feature scaling completed.")